### ISSUE TITLE
Social icons are linking wrong

### ISSUE THREAD

**Issue by IamSachin** [GavickPro/Portfolio-Free-Ghost-Theme#15]
I have replaced the line in footer.hbs with:
< a class="social__icon social__icon--fb" href="www.facebook.com/myprofilename/">Facebook</a>
(intentional space added at <a)

But the issue is, the icon on the website is linking it to: www.myblogaddress.com/www.facebook.com/myprofilename/ 
instead of just 
www.facebook.com/myprofilename/

**Comment by Bernjc** [comment]
You need to include `http://` before the link otherwise it does what you are seeing. This is how the href attribute works in HTML and is not something associated with the them or blog platform.

Change your link to the following and it should work fine:

`< a class="social__icon social__icon--fb" href="http://www.facebook.com/myprofilename/">Facebook</a>`

**Comment by IamSachin** [comment]
Oh yeah :( . Thank You Sire, I suddenly feel so stupid
